macro index,pager d "<save-message>=[Gmail]/Cestino<enter><enter><refresh>" "Trash Message"

set imap_user = "xxxxxxxxxx@gmail.com"
set imap_pass = ""
set smtp_url = "smtp://xxxxxxxxxx@smtp.gmail.com:587/"
set smtp_pass = ""
set from = "xxxxxxxxxxx@gmail.com"
set realname = "XXXXXXXXX"
set postponed = ""
set record = ""
